name: My Frist Worklfow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v6
            
            - name: List and Read files
              run: |
                echo "My frist Gihub Action" 
                ls
                cat README.md
            
            
              #   - name: List files
            #   run: ls
            
            # - name: Read file
            #   run: cat README.md
