name: Generate ASCII art

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              run: sudo apt-get install cowsay -y
  
            - name: Execute Cowsay 
              run: cowsay -f dragon "run for cover, I am a Dragon" >> dragon.txt
            
            - name: Upload dragon
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text
                path: dragon.txt

    test_job:
        needs: build_job
        runs-on: ubuntu-latest

        steps:
            - name: Download dragon
              uses: actions/download-artifact@v4
              with:
                name: dragon-text
           
  
            - name: Test Files 
              run: grep -i "dragon" dragon.txt
  
    deploy_job:
        needs: test_job
        runs-on: ubuntu-latest

        steps:
            - name: Download dragon
              uses: actions/download-artifact@v4
              with:
                name: dragon-text
            - name: Read File
              run: cat dragon.txt
  
       
            
